Item.create(name: "Water")
Item.create(name: "Toothbrush")
Item.create(name: "Razor")
Item.create(name: "Comb")
Item.create(name: "Cotton Swab")
Item.create(name: "Shampoo")
Item.create(name: "Hair Conditionair")
Item.create(name: "Body Wash")
Item.create(name: "Body Lotion")
Item.create(name: "Soap")
Item.create(name: "Toilet Paper")
